services:
  guildmaster:
    image: guildmaster
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    # Mount local assets so you can edit static files without rebuilding the image.
    # Remove this volume if you want the assets baked into the image instead.
    volumes:
      - ./assets:/app/assets:ro
